apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../../../base/argocd
  - applicationset-lab.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
